Repository jacobdeleon12/Sceneit, pull requests merged in 2019-08, with the labels that each got.

#109 Kaleb
  client/src/components/Iframe/style.css
  client/src/components/Wrapper/style.css
  client/src/components/mainWrapperVideos/index.js
Labels: enhancement, front end

#110 jumbo iframe made responsive and css done on colors and buttons
  client/src/components/Buttons/Google/index.js
  client/src/components/Buttons/Google/style.css
  client/src/components/Buttons/VideoBtns/style.css
  client/src/components/Iframe/style.css
  client/src/components/Wrapper/style.css
Labels: enhancement, front end

#111 console errors fixed
  client/src/components/Iframe/index.js
  client/src/components/Wrapper/index.js
Labels: bug, enhancement

#112 Blakes branch
  client/src/pages/Main.js
  client/src/pages/User.js
Labels: back-end

#116 Blakes branch
  client/src/components/Buttons/Google/index.js
  client/src/components/mainWrapperVideos/index.js
  client/src/pages/Main.js
  client/src/pages/SearchResults.js
  client/src/pages/User.js
  controllers/usersController.js
Labels: bug

#117 fixed paths and file names, and took out some console logs
  client/src/components/alert/index.js
  client/src/components/footer/index.js
  client/src/components/mainWrapperVideos/index.js
  client/src/components/splash/index.js
  client/src/components/tile/index.js
  client/src/pages/Main.js
  client/src/pages/User.js
Labels: bug

#119 saved user to sessionStorage instead of using DB api call. more work …
  client/src/components/Buttons/Google/index.js
  client/src/pages/Login.js
  client/src/pages/Main.js
  controllers/usersController.js
Labels: api

#120 Kaleb
  client/src/components/Buttons/Google/index.js
  client/src/components/Iframe/style.css
  client/src/components/Nav/index.js
  client/src/components/Userwrap/style.css
  client/src/components/Wrapper/style.css
  client/src/components/mainWrapperVideos/index.js
  client/src/components/splash/style.css
Labels: enhancement, front end

#122 Blakes branch
  client/src/components/Buttons/Google/index.js
  client/src/components/mainWrapperVideos/index.js
  client/src/pages/Main.js
  client/src/pages/User.js
  controllers/usersController.js
Labels: api, bug

#144 Blake branch
  client/src/components/AboutUs/index.js
  client/src/components/Footer/style.css
  client/src/components/MainWrapperVideos/index.js
  client/src/components/SearchWrapperVideos/index.js
  client/src/components/Userwrap/index.js
  client/src/pages/Main.js
  client/src/pages/User.js
Labels: api, bug, front end

#147 Blake branch
  client/src/components/AboutUs/index.js
  client/src/components/Userwrap/index.js
  client/src/pages/User.js
Labels: bug, front end

#149 Kaleb new branch
  client/src/components/Iframe/style.css
  client/src/components/Userwrap/index.js
  client/src/components/Wrapper/style.css
Labels: enhancement

#150 Blake branch
  client/src/components/AboutUs/index.js
  client/src/components/Buttons/Google/index.js
  client/src/components/MainWrapperVideos/index.js
  client/src/components/Userwrap/index.js
  client/src/components/Wrapper/style.css
  client/src/pages/Login.js
  client/src/pages/Main.js
  client/src/pages/User.js
  client/src/utils/API.js
  models/user.js
  routes/api/users.js
Labels: bug

#154 Kaleb new branch
  client/src/components/SearchWrapperVideos/index.js
  video/index.js
  video/playList.js
  video/reddit.js
  video/steam.js
  video/tmdb.js
  video/vimeo.js
  video/youtube.js
Labels: bug, server, video

#160 Blake branch
  client/src/components/Iframe/style.css
  client/src/components/Jumbotron/index.js
  client/src/components/Jumbotron/style.css
  client/src/components/MainWrapperVideos/index.js
  client/src/components/MainWrapperVideos/style.css
  client/src/components/Splash/style.css
  client/src/components/Userwrap/index.js
  client/src/components/Wrapper/style.css
Labels: bug

#167 Kaleb new branch
  client/src/components/MainWrapperVideos/index.js
  client/src/components/SearchWrapperVideos/index.js
  client/src/components/Wrapper/style.css
Labels: bug
