Repository jacobdeleon12/Sceneit, pull requests merged in 2019-07, with the labels that each got.

#6 initial files added
  client/README.md
  client/package-lock.json
  client/package.json
  client/public/favicon.ico
  client/public/index.html
  client/public/manifest.json
  client/src/App.js
  client/src/components/DeleteBtn/index.js
  client/src/components/DeleteBtn/style.css
  client/src/components/Form/index.js
  client/src/components/Grid/index.js
  client/src/components/Jumbotron/index.js
  client/src/components/List/index.js
  client/src/components/List/style.css
  client/src/components/Nav/index.js
  client/src/index.js
  client/src/pages/Books.js
  client/src/pages/Detail.js
  client/src/pages/NoMatch.js
  client/src/utils/API.js
  controllers/booksController.js
  models/book.js
  models/index.js
  package.json
  routes/api/books.js
  routes/api/index.js
  routes/index.js
  scripts/seedDB.js
  server.js
Labels: Deliverable

#11 Kalebs
  wireframe/FinalProjectTemplateWireframe.xd
Labels: Deliverable

#12 kalebs
  wireframe/FinalProjectTemplateWireframe.pdf
Labels: Deliverable

#13 Blakes branch
  wireframe/sceneItWireFrame.png
Labels: Deliverable

#41 Kalebs
  client/package-lock.json
  client/package.json
  client/src/components/Buttons/DeleteBtn/index.js
  client/src/components/Buttons/DeleteBtn/style.css
  client/src/components/Buttons/Google/index.js
  client/src/components/Buttons/Google/login.js
  client/src/components/Buttons/Google/logout.js
  client/src/components/Buttons/Google/style.css
  client/src/pages/Books.js
  config/passport-setup.js
  package-lock.json
  package.json
  routes/google/auth-routes.js
  server.js
Labels: front end

#44 Kalebs
  client/src/App.js
  client/src/components/Buttons/Google/login.js
  client/src/components/Buttons/Google/style.css
  client/src/components/Nav/index.js
  client/src/pages/Login.js
Labels: front end

#51 Kalebs
  client/src/App.js
  client/src/components/Nav/EditUserNav.js
  client/src/components/Nav/MainNav.js
  client/src/components/Nav/SearchNav.js
  client/src/components/Nav/SearchResultNav.js
  client/src/components/Nav/TitleNav.js
  client/src/components/Nav/UserNav.js
  client/src/components/Nav/index.js
  client/src/pages/Login.js
  client/src/pages/Main.js
  client/src/pages/Search.js
  client/src/pages/User.js
Labels: front end

#54 Kalebs
  client/src/App.js
  client/src/components/Iframe/index.js
  client/src/components/Iframe/style.css
  client/src/components/MovieCard/index.js
  client/src/components/Wrapper/index.js
  client/src/pages/Main.js
  client/src/pages/Search.js
  client/src/pages/SearchResults.js
  client/src/pages/Title.js
  client/src/pages/User.js
  client/src/utils/API.js
Labels: front end

#55 set up featured video and got the media queries set up for responsive
  client/src/components/JumboIframe/index.js
  client/src/components/JumboIframe/style.css
  client/src/components/Jumbotron/index.js
  client/src/pages/Main.js
Labels: front end

#56 Kalebs
  client/src/components/Buttons/SaveBtn/index.js
  client/src/components/Buttons/SaveBtn/style.css
  client/src/components/Iframe/index.js
  client/src/components/Iframe/style.css
  client/src/components/JumboIframe/index.js
  client/src/components/JumboIframe/style.css
  client/src/pages/Main.js
Labels: front end

#59 Blakes branch
  client/package-lock.json
  client/src/App.js
  client/src/components/Buttons/Google/login.js
  client/src/components/Buttons/SaveBtn/index.js
  client/src/components/Iframe/index.js
  client/src/components/Iframe/style.css
  client/src/components/Nav/MainNav.js
  client/src/pages/Main.js
  client/src/pages/Search.js
  client/src/pages/SearchResults.js
  client/src/pages/User.js
  client/src/utils/API.js
  controllers/usersController.js
  models/user.js
  package-lock.json
  routes/api/users.js
Labels: api, back-end

#60 Kalebs
  client/src/components/Carousel/index.js
  client/src/components/JumboIframe/index.js
  client/src/components/Jumbotron/index.js
  client/src/pages/Main.js
Labels: api, front end

#62 fixed semi-colon showing in page
  client/src/pages/Main.js
Labels: front end

#64 Blakes branch
  client/src/components/Buttons/Google/index.js
  client/src/components/Buttons/SaveBtn/index.js
  client/src/pages/Main.js
  client/src/pages/User.js
  client/src/utils/API.js
  controllers/usersController.js
  models/user.js
  routes/api/users.js
  server.js
Labels: back-end

#65 Kalebs
  client/src/components/Grid/index.js
  client/src/components/Nav/EditUserNav.js
  client/src/components/Nav/MainNav.js
  client/src/components/Nav/SearchNav.js
  client/src/components/Nav/SearchResultNav.js
  client/src/components/Nav/TitleNav.js
  client/src/components/Nav/UserNav.js
  client/src/components/Nav/index.js
  client/src/components/Wrapper/index.js
  client/src/pages/Main.js
Labels: front end

#66 got the movies showing again
  client/src/pages/Main.js
Labels: front end

#67 Kalebs
  client/src/components/Buttons/VideoBtns/index.js
  client/src/components/Buttons/VideoBtns/style.css
  client/src/components/Wrapper/style.css
  client/src/pages/Main.js
  client/src/pages/User.js
Labels: bug, server

#68 kalebs
  server.js
Labels: bug, server

#69 Blakes branch
  client/src/pages/Main.js
  client/src/pages/User.js
Labels: back-end

#71 Kalebs
  client/public/index.html
  client/src/components/Buttons/VideoBtns/style.css
  client/src/components/Nav/EditUserNav.js
  client/src/components/Nav/MainNav.js
  client/src/components/Nav/SearchNav.js
  client/src/components/Nav/SearchResultNav.js
  client/src/components/Nav/TitleNav.js
  client/src/components/Nav/UserNav.js
  client/src/components/Nav/index.js
  client/src/pages/Main.js
Labels: front end, help wanted

#76 Blakes branch
  client/src/components/Userwrap/index.js
  client/src/components/Userwrap/style.css
  client/src/pages/Main.js
  client/src/pages/User.js
  client/src/utils/API.js
  controllers/usersController.js
  routes/api/users.js
Labels: api, front end

#89 Kalebs
  client/src/components/Buttons/Google/index.js
  client/src/pages/Main.js
  client/src/pages/User.js
Labels: front end, pages

#90 Kalebs
  client/src/components/splash/index.js
  client/src/pages/Login.js
Labels: bug

#92 Kalebs
  client/src/components/Iframe/index.js
  client/src/components/Iframe/style.css
  client/src/pages/User.js
Labels: front end

#93 style added to splash page
  client/src/components/splash/index.js
  client/src/components/splash/style.css
Labels: front end

#95 Blakes branch
  client/src/components/Buttons/Google/index.js
  client/src/components/Buttons/VideoBtns/index.js
  client/src/components/splash/index.js
  client/src/pages/Login.js
  client/src/pages/Main.js
Labels: bug

#98 Kalebs
  client/src/components/Iframe/style.css
  client/src/components/Nav/EditUserNav.js
  client/src/components/Nav/MainNav.js
  client/src/components/Nav/SearchNav.js
  client/src/components/Nav/SearchResultNav.js
  client/src/components/Nav/TitleNav.js
  client/src/components/Nav/UserNav.js
  client/src/components/Nav/index.js
  client/src/components/splash/style.css
Labels: front end

#100 Kalebs
  client/src/components/Buttons/Google/index.js
  client/src/components/Wrapper/index.js
  client/src/pages/Login.js
  client/src/pages/Main.js
Labels: front end

#102 new branch new me
  client/src/components/Buttons/VideoBtns/style.css
  client/src/components/Wrapper/style.css
  client/src/pages/Main.js
Labels: front end
